# Future temperature scenarios

## Learning goals for this lesson {-#goals_future_temp_scen}

- Acquire background knowledge on some important concepts in climate change analysis
- Understand how future climate projections are generated
- Learn about the "generations" of climate models and greenhouse gas concentration scenarios
- Appreciate that it's important to use up-to-date scenarios when you're working in this space

## Impacts of future climate change

There is no doubt that man-made climate change has already affected our climate, and rising temperatures (and other changes) have left noticeable marks on the world's ecological and agricultural systems. Such impacts have been reported in many studies, with lots of solid evidence backing up the conclusions of these reports.

There is of course no credible reason to believe that climate change has already ended. In fact, we're expecting future impacts to be more dramatic than what we've seen so far. This is mainly because atmospheric greenhouse gas concentrations are now higher than they've ever been, since our species appeared on the planet (and in fact many millions of years before). Despite some efforts to mitigate climate change, the world's factories, cars etc. are also still emitting carbon dioxide on the order of 40 Gt CO~2~-eq per year - at or at least close to the all-time peak, with only weak signs of significant slowdown over the coming decades. We also know that near-global ecosystem degradation is gradually chipping away at the buffers, checks and balances that have managed to maintain stable ecosystems to date. To anticipate the future impacts of climate change, we have to keep all these dynamics in mind. It then becomes pretty obvious that we cannot predict with certainty what is going to happen in the future. We don't know to what extent global efforts to curb carbon dioxide emissions or sequester carbon from the atmosphere will be successful. We also don't know how much change the Earth's marine and terrestrial ecosystems will be able to absorb before irreversible and possibly self-reinforcing degradation will set in.

We can't address all uncertainties with `chillR` of course, but we can accommodate - to some extent - our uncertainty about future climatic conditions. In climate change adaptation research, the challenge is often conceptualized using the concept of exposure, sensitivity and adaptive capacity:

![Conceptual framework for evaluating vulnerability and adaptation to climate change [[@luedeling_IHC_adapt_2020]](https://www.actahort.org/members/showpdf?booknrarnr=1281_58)](pictures/adaptation_challenge.png)

In this concept, ***exposure*** describes the future conditions we expect, and ***sensitivity*** is the way the system responds to change. By combining exposure and sensitivity, we can determine the ***potential impact*** of expected conditions on the system of interest. These aren't necessarily the actual impacts, however, because the system may be able to adapt to some extent. This system attribute is often referred to as ***adaptive capacity***. Adaptation actions usually either aim to reduce system sensitivity (e.g. by choosing different tree cultivars) or to raise adaptive capacity (e.g. by establishing management options that allow dealing with chill shortfalls).

What exact aspects of this concept we're working on depends a bit on our interpretation of these terms. For the most part, we're looking at exposure, because we're producing scenarios of conditions that orchards will be confronted with in the future. However, our chill models consider - to some extent - the biological response of trees, which we could argue comes close to the concept of sensitivity. Yet we're not fully capturing this sensitivity, so I would place the analyses we're currently doing mostly within the exposure category.

## Future climate scenarios

We've already learned about future climate scenarios in the introductory materials on climate change. In the last lesson, we looked at how we can make historic chill scenarios, including some technical details that we'll need in this lesson. What is still missing now is a source of information on conditions that climate models predict for the place we're interested in.

Running climate models is pretty complicated, and we certainly won't do that here. This is a science of its own, and getting everything right, from GCM setup, to RCM implementation and downscaling is pretty tricky. In fact, there is probably no agreement on what *is* right. In principle, all the `chillR` functions work just as well with great future scenarios as they do with deeply flawed ones... so if you happen to be collaborating with a world-class climate modeling group, or you have access to state-of-the-art climate scenarios for your region, it may be a good idea to use those data. `chillR` can't keep track of all downscaling efforts that are going on, or be aware of all regional initiatives. It does, however, includes functions that allows us easy access to useful databases of climate information.

### Some background on climate models and warming pathways

Until November 2023, the best source of climate data that `chillR` had to offer was the `ClimateWizard` database, maintained by the Center for Tropical Agriculture (CIAT). Compared to most other sources of climate information, the `ClimateWizard` database has a major advantage: It facilitates easy access to point-specific data for climate scenarios produced by multiple climate models. Other data sources may contain more credible models, more models, more scenarios etc., but many only contain *gridded* climate data. This may mean that you first have to download climate data for a whole region, country, continent or planet, only to then extract information for just that one point you're interested in. Given that we need such datasets for $T_{min}$ and $T_{max}$ for each month of the year and probably for multiple climate models, climate change trajectories and downscaling methods, data transfer needs quickly become a major bottlenecks. Depending on the data source you select, the hard drive of the computer you're currently using may not be able to store all the information you'd need to download. `ClimateWizard` does this selection for us, and it only returns information for the coordinates we specified.

The original `ClimateWizard` tool, developed by [Dr. Evan Girvetz](https://scholar.google.de/citations?user=Yh2sQY4AAAAJ&hl=de) is actually a website with a proper user interface, where you can check out future climate scenarios. Rather than using this web interface, we can access the same information via [an API](http://climatewizard.ccafs-climate.org/service?lat=9.58&lon=-74.41&index=CDD&scenario=rcp45&gcm=ACCESS1-0&range=2041-2060&baseline=1980-2000&avg=true). This stands for *Application Programming Interface*, which is a tool that provides direct access to the information in a database, without the need to click through various pages on a website. [The API is described in a github repository, where you can find detailed descriptions](https://github.com/CIAT-DAPA/climate_wizard_api).

A caveat to this data source is that (to the best of my knowledge) it has not been updated to include the latest climate scenarios. Climate science evolves rapidly and models get better and better. More importantly, the type of warming scenarios that are recommended by the IPCC get updated with every major report they issue. These scenarios are produced by the [Coupled Model Intercomparison Project (CMIP)](https://en.wikipedia.org/wiki/Coupled_Model_Intercomparison_Project), a major effort to assemble the best that climate science has to offer in terms of future projections. CMIP is structured in phases. Phase 5 (CMIP5) went from 2010 to 2014 and it included a certain set of climate models. The following CMIP6 includes has a slightly different array of climate models, which (at the time of writing) represents the **state of the art** of climate science, as endorsed by the IPCC.

Another feature of these future projections that gets updated occasionally are the warming scenarios. Over the years, these have evolved from the [scenarios contained in the Special Report on Emission Scenarios (SRES)](https://en.wikipedia.org/wiki/Special_Report_on_Emissions_Scenarios) via the [Representative Concentration Pathways (RCPs)](https://en.wikipedia.org/wiki/Representative_Concentration_Pathway) to the currently recommended [Shared Socioeconomic Pathways (SSPs)](https://en.wikipedia.org/wiki/Shared_Socioeconomic_Pathways). Feel free to follow the links for more information in these scenarios. The SSPs are the latest generation of scenarios, which was published in 2021. If you want to produce **state-of-the-art** projections, these are the scenarios you should be using, and you should be using the outputs of the CMIP6 set of climate models.

Unfortunately, `ClimateWizard` only includes RCP scenarios, and it even only has two of these, which don't really bracket the full array of future climates that climate scientists consider plausible. We used these RCP scenarios for quite a while after the release of the SSPs, but it is becoming increasingly difficult to publish results that are based on these outdated visions of our climatic future. In the chapter on [Making CMIP5 scenarios with the `ClimateWizard`], I'll still provide instructions here on how to use it, but I'd encourage you to upgrade to the CMIP6 information.

## `Exercises` on future temperature scenarios {-#exercises_future_scenarios}

Please document all results of the following assignments in your `learning logbook`.

1) Briefly describe the differences between the RCPs and the SSPs (you may have to follow some of the links provided above).